---
title: "Travis_JKT"
author: "Travis Daun"
date: "12/19/2018"
output: 
  html_document:
    keep_md: true
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(dplyr)
library(tidyr)
library(ggplot2)

beers <- read.csv("Beers.csv")
breweries <- read.csv("Breweries.csv")
str(breweries)
str(beers)
#Remove any whitespace in state names
breweries$State <- gsub("\\s+", "", breweries$State)
#group and sumaarize by state
by_state <- breweries%>%group_by(State)%>%summarize('NumberOfBreweries' = n())

#merge beer data with brewery data
breweriesdf <- merge(breweries, beers, by.x = "Brew_ID", by.y ="Brewery_id")

colnames(breweriesdf) <- c("Brewery_ID", "Brewery Name", "City", "State", "Beer Name", "Beer_ID", "ABV", "IBU", "Style",
                           "Ounces")

i<-1
na_df <- data.frame()
while(i<=10) {
  na_df[1,i] <- sum(is.na(breweriesdf[,i]))
    i<- i+1
}
colnames(na_df)<- c("Brewery_ID", "Brewery Name", "City", "State", "Beer Name", "Beer_ID", "ABV", "IBU", "Style",
                    "Ounces")
na_df

#Median ABV and IBU by state
Medians <- breweriesdf%>%group_by(State)%>%summarise(Median_ABV = median(na.omit(ABV)), 
                                                        Median_IBU = median(na.omit(IBU)))

Medians%>%summarise(max = max(na.omit(Median_ABV)))
Medians%>%summarise(min = min(na.omit(Median_ABV)))

Medians%>%summarise(max = max(na.omit(Median_IBU)))
Medians%>%summarise(min = min(na.omit(Median_IBU)))


head(arrange(Medians, desc(Median_ABV)),3)
tail(arrange(Medians, desc(Median_ABV)),2)
head(arrange(Medians, desc(Median_IBU)),2)
tail(arrange(Medians, desc(Median_IBU)),3)

ggplot(data = Medians, aes(x=reorder(State, -Median_ABV), y=Median_ABV)) +
  geom_bar(stat="identity") +
  theme(axis.text.x = element_text(angle=90, hjust=1))

ggplot(data = Medians, aes(x=reorder(State, -Median_IBU), y=Median_IBU)) +
  geom_bar(stat="identity") +
  theme(axis.text.x = element_text(angle=90, hjust=1))

summary(Medians$Median_ABV)

ggplot(data=Medians) +
  geom_point(
    mapping = aes(x=Median_ABV, y=Median_IBU),
    position="jitter"
  )
ggplot(data=breweriesdf) +
  geom_point(mapping = aes(x=ABV, y=IBU),
             position = "jitter")
```
